name: Android Apk Release

on:
  
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build_apk:    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "17.x"
          cache: 'gradle'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.3.1"
          cache: true
      - name: Get dependencies
        run: flutter pub get      
      - name: Start release build
        run: flutter build apk --release
      - name: Upload APK
        uses: actions/upload-artifact@main
        with:
          name: apk-build
          path: build/app/outputs/apk/release
  publish_apk:
    name: Upload Android Beta to Firebase App Distribution
    needs: [build_apk]
    runs-on: ubuntu-latest
    steps:    
    - name: setup npm
      uses: actions/setup-node@v3
      with: 
        node-version: 18
    - name: Download Artifact
      uses: actions/download-artifact@master
      with:
        name: apk-build
    - name: install firebase cli
      run: npm install -g firebase-tools
    - name: publist app to distribution
      run: firebase appdistribution:distribute app-release.apk --app ${{secrets.FIREBASE_ANDROID_APPID}} --token ${{secrets.FIREBASE_TOKEN}} --testers "${{env.TESTERS}}"